### ISSUE TITLE
Missing Usage or Help output

### ISSUE THREAD

**Issue by jtreleaven** [RedVentures/okta-aws#1]
Arguably a requirement for any and all CLI tools would be some form of usage, help, or default output instructing the user.

**Comment by hasues** [comment]
Agreed.  It needs an explanation for how it integrates with the AWS SDK as well, for which if it doesn't access it, the tool does not work.

**Comment by connaryscott** [comment]
Yeah I give once i see this:

```
C02PQ6FEG3QD:oktaauth chscott$ okta-aws --help
Invalid profile, no match found for 
```

**Comment by james-huston** [comment]
Please use [oktad](https://github.com/redventures/oktad) instead of okta-aws.
