### ISSUE TITLE
Cannot use default profile

### ISSUE THREAD

**Issue by jtreleaven** [RedVentures/okta-aws#2]
Digging through the code a bit, it looks like the example in the readme `okta-aws -- /bin/bash` won't work because it expects there to be an argument passed in for profile. So it's required that you specify a profile as the first argument like `okta-aws <profile> -- /bin/bash`.

**Comment by hopkinsth** [comment]
I'm not sure I agree with this: do you have a role_arn in your default profile?

**Comment by james-huston** [comment]
It's based on the Okta application URL. The SAML returned from the Okta login places you in a default account. This should be permitted (in fact is required for our use case) but is currently broken in the latest versions. The original version I published worked but I broke it somewhere along the way.

**Comment by hopkinsth** [comment]
I think we might be talking about two different things? I think Jeff is asking for this tool to allow you to use the `[default]` profile in your `~/.aws/config`

Might be mistaken, though.

**Comment by james-huston** [comment]
yes, we are talking about different things. 

`[default]` is accessible by running `okta-aws default -- /bin/bash`. Having that as the actual default profile doesn't make sense in this scenario though because for this tool that is **always** set by the okta application/SAML.

**Comment by james-huston** [comment]
Please use [oktad](https://github.com/redventures/oktad) instead of okta-aws.
